# https://taskfile.dev

version: "3"

tasks:
  build:
    cmds:
      - cp {{.TINYGOROOT}}/targets/wasm_exec.js ./docs/
      - GOOS=js GOARCH=wasm tinygo build -o=./docs/main.wasm ./cmd/wasm
    vars:
      TINYGOROOT:
        sh: tinygo env TINYGOROOT

  test:
    cmds:
      - go test -race -count=1 .

  serve:
    cmds:
      - go run github.com/eliben/static-server@latest
