# https://taskfile.dev

version: "3"

tasks:
  build:
    cmds:
      - cp {{.GOROOT}}/lib/wasm/wasm_exec.js ./public/
      - GOOS=js GOARCH=wasm go build -o=./public/main.wasm ./cmd/wasm
    vars:
      GOROOT:
        sh: go env GOROOT

  serve:
    cmds:
      - go run github.com/eliben/static-server@latest
