# https://taskfile.dev

version: "3"

tasks:
  build:
    cmds:
      - cp {{.TINYGOROOT}}/targets/wasm_exec.js ./docs/
      - GOOS=js GOARCH=wasm tinygo build -o=./docs/main.wasm ./cmd/wasm
    vars:
      TINYGOROOT:
        sh: tinygo env TINYGOROOT

  test:
    cmds:
      - go test -race -count=1 .

  serve:
    cmds:
      - go run github.com/eliben/static-server@latest

  download:
    cmds:
      - curl -o eff_large_wordlist.txt https://www.eff.org/files/2016/07/18/eff_large_wordlist.txt
    sources:
      - Taskfile.yml
    generates:
      - eff_large_wordlist.txt
